### ISSUE TITLE
in this case you don't need a constructor

### ISSUE THREAD

**Issue by motifej** [Nortsova/react_redux#2]
https://github.com/Nortsova/react_redux/blob/4efe7673d7df7ec1aaa80fc9eaa51ccc9623f4b8/src/components/Form.js#L5-L16

# use : 
```
state = {}

handleChange = ({ target }) => this.setState({ title: target.value });

**Comment by Nortsova** [comment]
fixed

**Comment by motifej** [comment]
should fix it in all your code
