### ISSUE TITLE
Should use arrow function

### ISSUE THREAD

**Issue by motifej** [Nortsova/react_redux#5]
https://github.com/Nortsova/react_redux/blob/4efe7673d7df7ec1aaa80fc9eaa51ccc9623f4b8/src/components/List.js#L6-L9

### Should use arrow function

```
const List = ({ data }) => (
  <ul className='task-list'> 
     { data.map(el => <li>{el.name}</li>) }
  </ul>
);

**Comment by Nortsova** [comment]
fixed
